### ISSUE TITLE
User can filter policies by year passed

### ISSUE THREAD

**Issue by chrisaballard** [climatepolicyradar/cpr-issues#103]
The user should be able to filter policies by the year that the policy was passed, by determining a range of years (min-max). 

A range slider will be used to set the min and the max years. The range of dates displayed on the slider will be hardcoded (1947?-2021).

Creating a multi-thumb slider will require some extra time. Following these two blog/tutorials:

https://css-tricks.com/multi-thumb-sliders-particular-two-thumb-case/
https://css-tricks.com/multi-thumb-sliders-general-case/

**Comment by eurolife** [comment]
The UI and API integration is complete for this and ready for review.
