### ISSUE TITLE
Research > Evaluate Adobe extract API 

### ISSUE THREAD

**Issue by chrisaballard** [climatepolicyradar/cpr-issues#105]
Test the Adobe PDF Extract API
https://www.adobe.io/apis/documentcloud/dcsdk/pdf-extract.html

Figure out if it substantialy improves our text extraction and what benefits it gives us

## Steps

- [x] set up a framework to parse PDFs
- [x] select a test set of PDFs to parse. This should be distributed across document types and layouts as much as possible. All documents should be English language.
- [x] split longer PDFs so they can be parsed. This should very naively split them for now, even though this may cause problems with the ML-based parsing (to be further investigated).
- [ ] ~write a script to convert API results to nested JSON~
- [x] write a script to convert API results to HTML
- [x] evaluate the effectiveness of the API given the above work

### When evaluating, think about...

* the accuracy of text parsing
* how the hierarchy could be useful to us
* how well different document features are processed (text boxes, multiple columns, contents pages, appendices, figures, tables, footnotes)
* the number of credits used -> cost
* how we could potentially do something like this ourselves

**Comment by kdutia** [comment]
@chrisaballard my evaluation of the Adobe Extract API and recommended next steps for us are in [this Notion document](https://www.notion.so/climatepolicyradar/Adobe-PDF-Extract-API-evaluation-cbc4ed980eb84762907d24e041a67542). Happy to talk through these whenever's good for you.
