### ISSUE TITLE
Mockup requirement - 'Overview' page

### ISSUE THREAD

**Issue by marcusodavies** [climatepolicyradar/cpr-issues#123]
This view will:

- Be hard-coded
- Be accessed by clicking on 'overview' – next to 'policy search' – at the top of the page.
- Display coloured 'bubbles' of concepts, each containing specific keywords (as per our ['bubbles' CSV](https://docs.google.com/spreadsheets/d/1B35Dwa-fvzUTxZHCJgzpjLdv7M9-uWL-/edit#gid=1126445969))

If displayed without the user having made a search: 

- all concept 'bubbles' will be displayed. 

If displayed after the user has made a search:

- only concept bubbles relating to the search term will be displayed. 
- each bubble will display an (approximate) number, indicating how many instances of the concept in the results are linked to the search term
- two instruments within the instrument bubble will be clickable. When an instrument is clicked on, a hard-coded results page will be displayed, showing all the in-text instances of that instrument.

![image](https://user-images.githubusercontent.com/8472119/139216919-2309056c-5418-495e-8c7a-e23a2e091e16.png)

![image.png](https://images.zenhubusercontent.com/61387fb7f402af380e78f268/0d0decf0-9fd8-4cf6-8d22-0916e65b86cb)

**Comment by eurolife** [comment]
The overview page is completed and the Food and Gender bubbles are clickable as specified by Marcus. There are some issues with the multi-id policy API where some ID's cause a server error. This has been noted in open issue #113 .
