### ISSUE TITLE
Add non-functional download button and search message to search results page

### ISSUE THREAD

**Issue by marcusodavies** [climatepolicyradar/cpr-issues#128]
1) 'Download results' button
2) This message is displayed on the results page: 'We're also showing results containing terms related to your query'.

[Annotated screenshots](https://docs.google.com/presentation/d/1RqviIpZkjbwHgXnaulJZyCSP9ycxE8UJp6L4hySFJ9k/edit#slide=id.p).

**Comment by eurolife** [comment]
These two items are done and ready for review.
