### ISSUE TITLE
Setup github issue tracking, projects and repositories

### ISSUE THREAD

**Issue by chrisaballard** [climatepolicyradar/cpr-issues#2]

**Comment by tofferb** [comment]
Agreed with @michal-nachmany that we would add repo for cpr-website, so that issues can be added there ready for next sprint

**Comment by chrisaballard** [comment]
@michal-nachmany Let's wait before we create the repo for the website until we have a clearer idea of the framework we're going to use (e.g. if we host a static site via github pages or not). In the meantime, please create issues in the cpr-issues repo.
