### ISSUE TITLE
Review user journies slidedeck

### ISSUE THREAD

**Issue by chrisaballard** [climatepolicyradar/cpr-issues#20]
@tofferb commented on [Wed Sep 08 2021](https://github.com/climatepolicyradar/policy-search/issues/1)

**Comment by tofferb** [comment]
Review Marcus' [user journies slidedeck](https://docs.google.com/presentation/d/1mPf-XPrTMelUW4bVDv61xqIkR138CQc0/edit#slide=id.p1)
